### ISSUE TITLE
User icon gets rendered behind popout

### ISSUE THREAD

**Issue by Exhabition** [Discord-Theme-Addons/statuspicker-plus#1]
![image](https://user-images.githubusercontent.com/63742759/121772308-e4c9b000-cb74-11eb-9ee5-26380cc2bafc.png)

So whenever I open the popout, it only shows the gray circle, messing with the positions a bit shows that the icon is at the correct position, but just put behind the popout.
![image](https://user-images.githubusercontent.com/63742759/121772345-2a867880-cb75-11eb-9ec7-8eda693f3b91.png)

I tried a bunch of stuff, but most solutions ended up having side effects for other elements. I don't have any other styles installed other then have some CSS to change channel hovers and selecting them. This shouldn't interfere with this theme if I am correct.
Simply changing z-index's didn't work either or ended up interfering with other elements.

Asking for a solution and if people are experiencing this too, appreciated

**Comment by o1x3** [comment]
+1

**Comment by LuckFire** [comment]
should be fixed
